version: '3.8'
services:
  invoice-service:
    build:
      context: ./invoice-service
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/invoice
      - RABBITMQ_URI=amqp://rabbitmq:5672
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - MONGO_URI=mongodb://mongo:27017/email
      - RABBITMQ_URI=amqp://rabbitmq:5672
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  mongo:
    image: mongo:4.2
    ports:
      - '27017:27017'
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
